<?php

/**
 * Implements hook_menu().
 * @return array
 */
function export_node_menu() {
  $items = array();

  $items['node/%/export'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_export_node_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  $items['export_nodes/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_export_nodes_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $items['admin/settings/export_node'] = array(
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('export_node_admin'),
    'access arguments' => array('administer export_node settings'),
    'title' => t('Export node settings'),
    'description' => t('Administer export node'),
  );

  return $items;
}

/**
 * Implements hook_admin().
 *
 * Adds the possibility to add htaccess data to the image src path.
 * @return mixed
 */
function export_node_admin() {
  $form = array();
  $form['node_export_dev_mode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Activate Devel mode'),
    '#default_value' => variable_get('node_export_dev_mode', 0),
  );

  $form['node_export_dev_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host domain'),
    '#default_value' => variable_get('node_export_dev_host'),
  );

  $form['node_export_htaccess_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Htaccess User'),
    '#default_value' => variable_get('node_export_htaccess_user'),
  );

  // @todo: hash pw.
  $form['node_export_htaccess_pw'] = array(
    '#type' => 'textfield',
    '#title' => t('Htaccess password'),
    '#default_value' => variable_get('node_export_htaccess_pw'),
  );

  return system_settings_form($form);
}

function export_node_admin_validate($form, &$form_state) {

}

/**
 * Export node page callback.
 * Returns json for a specific node.
 * @param null $arg
 */
function _export_node_callback($arg = NULL) {
  $node = node_load($arg);

  // Exit if node does not exist or is not published.
  if (!$node || $node->status == 0) {
    drupal_json_output(array('Access denied'));
    drupal_exit();
  }

  $lang = $node->language;
  $ids = array();
  $images = array();

  // Get the image.
  foreach ($node->field_media_image[$lang] as $k) {
    $ids[] = $k['value'];
  }

  $fc_items = field_collection_item_load_multiple($ids);
  foreach ($fc_items as $k => $v) {
    $img_vars = array(
      'style_name' => 'mobile_1',
      'path' => $v->field_fc_image[$lang][0]['uri'],
      'alt' => $v->field_fc_image[$lang][0]['alt'] . ' - Foto: ' . $v->field_fc_copyright[$lang][0]['safe_value'],
      'title' => $v->field_fc_image[$lang][0]['title'] . ' - Foto: ' . $v->field_fc_copyright[$lang][0]['safe_value'],
    );

    $image = theme_image_style($img_vars);
    $images[] = array(
      'image' => $image,
      'caption' => $v->field_fc_headline[$lang][0]['safe_value'],
      'copyright' => $v->field_fc_copyright[$lang][0]['safe_value'],
    );
  }

  // Get the node before the current.
  $q = "SELECT n.nid
        FROM {node} n
        JOIN {field_data_field_rubric} r
        ON n.nid = r.entity_id
        WHERE r.field_rubric_tid = :tid AND n.created < :created
        LIMIT 1";
  $result = db_query($q, array(':tid' => $node->field_rubric[$lang][0]['tid'], ':created' => $node->created));
  $prev_nid = $result->fetchAssoc();

  // Get the node posted after the current one.
  $q = "SELECT n.nid
        FROM {node} n
        JOIN {field_data_field_rubric} r
        ON n.nid = r.entity_id
        WHERE r.field_rubric_tid = :tid AND n.created > :created
        LIMIT 1";
  $result = db_query($q, array(':tid' => $node->field_rubric[$lang][0]['tid'], ':created' => $node->created));
  $next_nid = $result->fetchAssoc();

  // Prepare json.
  $json = array(
    'images' => $images,
    'headline' => $node->title,
    'kicker' => $node->field_kicker[$lang][0]['safe_value'],
    'body' => $node->body[$lang][0]['safe_value'],
  );

  if ($prev_nid) {
    $json['prev_nid'] = $prev_nid['nid'];
  }
  if ($next_nid) {
    $json['next_nid'] = $next_nid['nid'];
  }

  drupal_json_output($json);
  drupal_exit();
}

/**
 * Export nodes callback.
 * Generates json output with nodes by category.
 * @param string $arg
 */
function _export_nodes_callback($arg = 'all') {
  // Init variables.
  $node = FALSE; // Node loaded.
  $lang = 'und'; // Node's language.
  $image = FALSE; // Image loaded (field collection item).
  $term = ''; // Node Category.
  $copyright = ''; // Copyright string.
  $alt = ''; // Image alt text.
  $title = ''; // Image title text.
  $result = NULL; // query result.
  $json = array(); // Json output.

  if ($arg == 'all') {
    $q = "SELECT n.nid
        FROM {node} n
        JOIN {field_data_field_rubric} r
        ON n.nid = r.entity_id";
  }
  else {
    $q = "SELECT n.nid
        FROM {node} n
        JOIN {field_data_field_rubric} r
        ON n.nid = r.entity_id
        JOIN {taxonomy_term_hierarchy} h
        ON r.field_rubric_tid = h.tid
        WHERE r.field_rubric_tid = :tid OR h.parent = :tid";
  }

  $result = db_query($q, array(':tid' => $arg));

  foreach ($result as $record) {
    $node = node_load($record->nid);
    $lang = $node->language;
    $image = field_collection_item_load($node->field_media_image[$lang][0]['value']);
    $term = taxonomy_term_load($node->field_rubric[$lang][0]['tid'])->name;

    if (!empty($image->field_fc_copyright[$lang][0]['safe_value'])) {
      $copyright = ' - Foto: ' . $image->field_fc_copyright[$lang][0]['safe_value'];
    }

    if (!empty($image->field_fc_image[$lang][0]['alt'])) {
      $alt = $image->field_fc_image[$lang][0]['alt'];
    }

    if (!empty($image->field_fc_image[$lang][0]['title'])) {
      $title = $image->field_fc_image[$lang][0]['title'];
    }

    $img_vars = array(
      'style_name' => 'mobile_1',
      'path' => $image->field_fc_image[$lang][0]['uri'],
      'alt' => $alt . $copyright,
      'title' => $title . $copyright,
      'width' => '',
      'height' => '',
    );
    $image = theme_image_style($img_vars);

    $json[] = array(
      'nid' => $node->nid,
      'tid' => $node->field_rubric[$lang][0]['tid'],
      'image' => $image,
      'term' => $term,
      'headline' => $node->title,
      'kicker' => $node->field_kicker[$lang][0]['safe_value'],
    );
  }
  drupal_json_output($json);
  drupal_exit();
}
